# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'artmonious' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for artmonious

    pod "Koloda"

  target 'artmoniousTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'artmoniousUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
